DATA:
  TRAIN_IMG_DATA: "datasets/second_stage/bimodal_resnet18_extract/train"
  VALID_IMG_DATA: "datasets/second_stage/bimodal_resnet18_extract/valid"
  TEST_IMG_DATA: "datasets/second_stage/bimodal_resnet18_extract/test"
DATA_LOADER:
  NAME: "second_stage_data"
  SECOND_STAGE:
    METHOD: "spectrum"
    TYPE: "pred"
  TRAIN_BATCH_SIZE: 64
  NUM_WORKERS: 0
MODEL:
  NAME: "spectrum_conv_model"
  SPECTRUM_CHANNEL: 80
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.001
  MILESTONE: [20,]
TRAIN:
  TRAINER: "SpectrumTrainer"
  MAX_EPOCH: 30
  OUTPUT_DIR: "results_second_stage/spectrum_on_pred/03_bimodal_resnet18_spectrom"
