DATA:
  ROOT: "datasets/chalearn2021"
  SESSION: "animal"
  TYPE: "face"
DATA_LOADER:
  NAME: "true_per_vat_data_loader"
  TRANSFORM: "set_vat_transform_op"
  TRAIN_BATCH_SIZE: 4
  NUM_WORKERS: 8
MODEL:
  NAME: "vat_model"
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.001
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [60, 80]
TRAIN:
  TRAINER: "ImageModalTrainer"
  MAX_EPOCH: 100
  LOG_INTERVAL: 10
  VALID_INTERVAL: 10
  OUTPUT_DIR: "results_true_personality/unified_face_images_animal/07_vat"
