DATA:
  ROOT: "datasets/chalearn2021"
  TYPE: "face"
DATA_LOADER:
  NAME: "true_personality_dataloader"
  TRANSFORM: "standard_frame_transform"
  TRAIN_BATCH_SIZE: 8
  NUM_WORKERS: 4
MODEL:
  NAME: "swin_transformer_true_personality"
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.001
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [3, 4]
TRAIN:
  TRAINER: "ImageModalTrainer"
  MAX_EPOCH: 5
  LOG_INTERVAL: 50
  OUTPUT_DIR: "results_true_personality/unified_face_images_talk/03_swin_transformer"
