DATA:
  TRAIN_IMG_DATA: "datasets/second_stage/swin_transformer_extract/train"
  VALID_IMG_DATA: "datasets/second_stage/swin_transformer_extract/valid"
  TEST_IMG_DATA: "datasets/second_stage/swin_transformer_extract/test"
DATA_LOADER:
  NAME: "second_stage_data"
  SECOND_STAGE:
    METHOD: "spectrum"
    TYPE: "feat"
  TRAIN_BATCH_SIZE: 2
  NUM_WORKERS: 0
MODEL:
  NAME: "spectrum_Feat_conv_model"
  SPECTRUM_CHANNEL: 512
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.01
  MILESTONE: [40,]
TRAIN:
  TRAINER: "SpectrumTrainer"
  MAX_EPOCH: 50
  OUTPUT_DIR: "results_second_stage/spectrum_on_pred/10_swin_spectrum"
