DATA:
  ROOT: "datasets/chalearn2021"
  SESSION: "talk"
  TYPE: "frame"
DATA_LOADER:
  NAME: "true_personality_dataloader"
  TRANSFORM: "standard_frame_transform"
  TRAIN_BATCH_SIZE: 16
  NUM_WORKERS: 0
MODEL:
  NAME: "interpret_dan_model_true_personality"
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.001
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [3, 4]
TRAIN:
  TRAINER: "ImageModalTrainer"
  MAX_EPOCH: 4
  LOG_INTERVAL: 50
  OUTPUT_DIR: "results_true_personality/unified_frame_images_talk/08_interpret_img.yaml"
