DATA_LOADER:
  NAME: "tpn_data_loader"
  TRANSFORM: "set_tpn_transform_op"
  TRAIN_BATCH_SIZE: 4
MODEL:
  NAME: "tpn_model"
SOLVER:
  LR_INIT: 0.001
TRAIN:
  TRAINER: "TPNTrainer"
  OUTPUT_DIR: "results/unified_frame_images/13_tpn"
